### PR TITLE
fix: Made OCR related options appear for LLM whisperer

### PR DESCRIPTION
**Pull request by chandrasekharan-zipstack**
## What

- Made options for OCR - `gaussian blur radius` and `median filter size` appear at all times
- Added option `force_text_processing` and defaulted it to false
- Adapters version was not bumped explicitly since it'd done in [this PR](https://github.com/Zipstack/unstract-adapters/pull/23)
- Made password field of postgres vectorDB as protected

## Why

- These settings are using even in case of `text` mode since `ocr` works internally in case of failures. They need to be configurable in that case
- In case `Force text processing` is True - we need not use OCR at all so these fields need not be present. A todo item is to render them conditionally - due to the time constraint we'll proceed with this

## How

...

## Relevant Docs

-

## Related Issues or PRs

-

## Dependencies Versions / Env Variables

-

## Notes on Testing

...

## Screenshots

image

## Checklist

I have read and understood the [Contribution Guidelines]().

### CODE REVIEW

**Review by athul-rs — APPROVED** [review]
LGTM.

@chandrasekharan-zipstack so both filter settings will now be available for 'ocr' as well as 'text' ? Hope there aren't any validation issues, related to this.

**Review by gaya3-vijayakumar — APPROVED** [review]
Looks good

**Review by gaya3-vijayakumar — APPROVED** [review]
Looks fine...

**Comment by athul-rs** [comment]
:+1:

**Pull request merged**
