### PR TITLE
fix/adapter-field-name-change

### PR DESCRIPTION
**Pull request by jaags-dev**
## What
 - Change the field name  from  "<Adapter> Adapter ID" to  "Name"

## Why
- More understandable this way.

## How

...

## Relevant Docs

-

## Related Issues or PRs

- https://zipstack.atlassian.net/browse/UN-1142

## Dependencies Versions / Env Variables

-

## Notes on Testing

...

## Screenshots
image

...

## Checklist

I have read and understood the [Contribution Guidelines]().

### CODE REVIEW

**Review by chandrasekharan-zipstack — COMMENTED** [review]
If this is a patch fix, please bump the patch version in [__init__.py](https://github.com/Zipstack/unstract-adapters/blob/b08d1744591bbcf951846e4d4696f29bafcc873a/src/unstract/adapters/__init__.py#L1). Otherwise increment the minor version if it might break something. Once approved and merged, we should release the same. Downstream updates can follow based on need

**Review by gaya3-vijayakumar — COMMENTED** [review]
Looks mainly a UI change. @jagadeeswaran-zipstack is that right?

**Comment by jaags-dev** [comment]
> Looks mainly a UI change. @jagadeeswaran-zipstack is that right?

Yes. Changes only gets reflected on UI.

**Review by chandrasekharan-zipstack — APPROVED** [review]
LGTM

**Review by gaya3-vijayakumar — APPROVED** [review]
Looks fine

**Review by chandrasekharan-zipstack — APPROVED** [review]

**Pull request merged**
